package com.llmcouncil.mobile
import android.app.Application
import android.content.Intent
import android.net.Uri
import androidx.core.content.ContextCompat
import androidx.lifecycle.*
import com.llmcouncil.mobile.data.*
import com.llmcouncil.mobile.model.*
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*
class RepoAuditViewModel(private val app:Application):AndroidViewModel(app){private val settings=SecureSettings(app);private val github=GitHubClient(settings);val run:StateFlow<RepoAuditRun> = RepoAuditRuntime.run;private val _repos=MutableStateFlow<List<GitHubRepo>>(emptyList());val repos=_repos.asStateFlow();private val _loading=MutableStateFlow(false);val loading=_loading.asStateFlow();private val _message=MutableStateFlow<String?>(null);val message=_message.asStateFlow();init{RepoAuditRuntime.initialise(app);CouncilRuntime.initialise(app)}
 fun githubConfigured()=settings.getGitHubToken().isNotBlank();fun saveGitHubToken(v:String){settings.setGitHubToken(v.trim());if(v.isNotBlank())loadRepos()};fun loadRepos(){if(_loading.value)return;viewModelScope.launch{_loading.value=true;_message.value=null;try{_repos.value=github.listRepos()}catch(e:Exception){_message.value=e.message?:e.toString()}finally{_loading.value=false}}}
 fun start(repo:GitHubRepo,ref:String){if(run.value.stage in listOf(RepoAuditStage.SNAPSHOT,RepoAuditStage.INDEPENDENT,RepoAuditStage.PEER_REVIEW,RepoAuditStage.VERIFY,RepoAuditStage.CHAIRMAN))return;ContextCompat.startForegroundService(app,Intent(app,RepoAuditService::class.java).apply{action=RepoAuditService.ACTION_START;putExtra(RepoAuditService.EXTRA_REPO,repo.fullName);putExtra(RepoAuditService.EXTRA_REF,ref.ifBlank{repo.defaultBranch})})};fun cancel(){app.startService(Intent(app,RepoAuditService::class.java).apply{action=RepoAuditService.ACTION_CANCEL})};fun clear(){RepoAuditRuntime.clear(app)}
 fun setExportTree(uri:Uri){settings.setExportTreeUri(uri.toString());_message.value="Export workspace saved"};fun exportTree():Uri?=settings.exportTreeUri()?.let(Uri::parse);fun exportCurrent(){val uri=exportTree();if(uri==null){_message.value="Choose an export workspace folder first";return};val current=run.value;if(current.repoFullName.isBlank()){_message.value="No repository audit is available to export";return};viewModelScope.launch{_loading.value=true;try{_message.value="Exported repository audit to "+withContext(Dispatchers.IO){ExportManager.exportRepoAudit(app,uri,current)}}catch(e:Exception){_message.value="Export failed: ${e.message?:e}"}finally{_loading.value=false}}};fun exportLastCouncil(){val uri=exportTree();if(uri==null){_message.value="Choose an export workspace folder first";return};val council=CouncilRuntime.run.value;if(council.question.isBlank()){_message.value="No standard council run is available to export";return};viewModelScope.launch{_loading.value=true;try{_message.value="Exported council run to "+withContext(Dispatchers.IO){ExportManager.exportCouncilRun(app,uri,council)}}catch(e:Exception){_message.value="Council export failed: ${e.message?:e}"}finally{_loading.value=false}}};fun clearMessage(){_message.value=null}}
