package com.llmcouncil.mobile.domain
import com.llmcouncil.mobile.data.*
import com.llmcouncil.mobile.model.*
import kotlinx.coroutines.*
import kotlinx.coroutines.sync.*
import kotlin.math.round
class CouncilEngine(private val client:OpenRouterClient,private val settings:SecureSettings,private val healthDb:ModelHealthDb){companion object{private const val S1=2048;private const val S2=1536;private const val S3=3072}
 private suspend fun trackedChat(model:String,prompt:String,maxTokens:Int):String=try{val text=client.chat(model,prompt,maxTokens);if(text.isBlank())throw IllegalStateException("Model returned an empty response");withContext(Dispatchers.IO){healthDb.record(model,true)};text}catch(e:Exception){withContext(Dispatchers.IO){healthDb.record(model,false,e.message?:e.toString())};throw e}
 suspend fun run(question:String,resume:CouncilRun?=null,onUpdate:suspend(CouncilRun)->Unit):CouncilRun=coroutineScope{val configured=settings.councilModels();var run=resume?.takeIf{it.question==question&&it.stage !in listOf(CouncilStage.COMPLETE,CouncilStage.CANCELLED)}?:CouncilRun(question,stage=CouncilStage.STAGE1);onUpdate(run);val ids=try{client.models().map{it.id}.toSet()}catch(_:Exception){emptySet()};val unavailable=if(ids.isEmpty())emptyList()else configured.filter{it !in ids};val selected=if(ids.isEmpty())configured else configured.filter{it in ids};val pre=unavailable.associateWith{"Model is no longer present in the currently configured provider catalogues. Choose a replacement in Models."};if(selected.size<2&&run.stage1.isEmpty()){run=run.copy(stage=CouncilStage.ERROR,errors=pre+("Council" to "Stage 1 cannot start: fewer than two currently available council models are selected."),finishedAt=System.currentTimeMillis());onUpdate(run);return@coroutineScope run};val sem=Semaphore(settings.maxConcurrency());val stage1:List<ModelAnswer>;val resumed=run.stage1.filter{it.error==null&&it.text.isNotBlank()};if(run.stage1.isNotEmpty()&&resumed.size>=2){stage1=run.stage1;run=run.copy(stage=CouncilStage.STAGE2,finishedAt=null);onUpdate(run)}else{run=run.copy(stage=CouncilStage.STAGE1,stage1=emptyList(),stage2=emptyList(),aggregate=emptyList(),chairman=null,finishedAt=null);onUpdate(run);stage1=selected.map{model->async{sem.withPermit{val t=System.currentTimeMillis();try{ModelAnswer(model,trackedChat(model,question,S1),System.currentTimeMillis()-t)}catch(e:Exception){ModelAnswer(model,"",System.currentTimeMillis()-t,e.message?:e.toString())}}}}.awaitAll();run=run.copy(stage1=stage1,errors=pre+stage1.mapNotNull{it.error?.let{e->it.model to e}}.toMap());onUpdate(run)};val ok1=stage1.filter{it.error==null&&it.text.isNotBlank()};if(ok1.size<2){run=run.copy(stage=CouncilStage.ERROR,errors=run.errors+("Council" to "Stopped after Stage 1: ${ok1.size}/${stage1.size.coerceAtLeast(selected.size)} available models produced usable answers. At least two are required for peer review."),finishedAt=System.currentTimeMillis());onUpdate(run);return@coroutineScope run};val labels=linkedMapOf<String,String>();val responses=buildString{ok1.forEachIndexed{i,a->val l="Response ${('A'.code+i).toChar()}";labels[l]=a.model;if(isNotEmpty())append("\n\n");append("$l:\n${a.text}")}};val rankPrompt="""Evaluate the anonymized responses to this question:
$question

$responses

Evaluate each response, then end with exactly:
FINAL RANKING:
1. Response X
2. Response Y
List only response labels in that final section.""";val stage2:List<RankingReview>;if(run.stage2.isNotEmpty()){stage2=run.stage2;run=run.copy(stage=CouncilStage.STAGE3,finishedAt=null);onUpdate(run)}else{run=run.copy(stage=CouncilStage.STAGE2,finishedAt=null);onUpdate(run);stage2=ok1.map{it.model}.map{model->async{sem.withPermit{val t=System.currentTimeMillis();try{val text=trackedChat(model,rankPrompt,S2);RankingReview(model,text,parseRanking(text),System.currentTimeMillis()-t)}catch(e:Exception){RankingReview(model,"",emptyList(),System.currentTimeMillis()-t,e.message?:e.toString())}}}}.awaitAll();run=run.copy(stage2=stage2,aggregate=aggregate(stage2,labels),errors=run.errors+stage2.mapNotNull{it.error?.let{e->"${it.model} (review)" to e}}.toMap());onUpdate(run)};if(run.aggregate.isEmpty()){run=run.copy(aggregate=aggregate(stage2,labels));onUpdate(run)};run=run.copy(stage=CouncilStage.STAGE3,finishedAt=null);onUpdate(run);val s1=ok1.joinToString("\n\n"){"Model: ${it.model}\nResponse: ${it.text}"};val s2=stage2.filter{it.error==null&&it.text.isNotBlank()}.joinToString("\n\n"){"Model: ${it.model}\nRanking: ${it.text}"};val prompt="""You are the Chairman of OmniCouncil. Synthesize the independent responses and peer rankings into one accurate answer.
Original question: $question

Independent responses:
$s1

Peer reviews:
$s2

Preserve important disagreements and do not treat consensus alone as proof.""";val configuredChairman=settings.chairman();val survivors=ok1.map{it.model}.toSet();val chairmanModel=if(configuredChairman in survivors)configuredChairman else ok1.first().model;val t=System.currentTimeMillis();val chairman=try{ModelAnswer(chairmanModel,trackedChat(chairmanModel,prompt,S3),System.currentTimeMillis()-t)}catch(e:Exception){ModelAnswer(chairmanModel,"",System.currentTimeMillis()-t,e.message?:e.toString())};run=if(chairman.error==null)run.copy(stage=CouncilStage.COMPLETE,chairman=chairman,finishedAt=System.currentTimeMillis())else run.copy(stage=CouncilStage.ERROR,chairman=chairman,errors=run.errors+("$chairmanModel (chairman)" to chairman.error!!),finishedAt=System.currentTimeMillis());onUpdate(run);run}
 private fun parseRanking(text:String)=Regex("Response [A-Z]").findAll(text.substringAfter("FINAL RANKING:",text)).map{it.value}.toList().distinct();private fun aggregate(reviews:List<RankingReview>,labels:Map<String,String>):List<AggregateRank>{val p=linkedMapOf<String,MutableList<Int>>();reviews.filter{it.error==null}.forEach{r->r.parsedRanking.forEachIndexed{i,l->labels[l]?.let{m->p.getOrPut(m){mutableListOf()}.add(i+1)}}};return p.map{(m,v)->AggregateRank(m,round((if(v.isEmpty())999.0 else v.average())*100)/100,v.size)}.sortedBy{it.averageRank}}
}
